
let json = [{
    "en" : {
        "SignIn": {
            "EmailAddress" : "Email Address",
            "Password" : "Password",
            "SignIn" : "Sign In",
            "SignUp" : "Don't have an account? Sign Up",
            "SuccessLog" : "User Logged In Successfully"
        },
        "SignUp" : {
            "SignUp" : "Sign up",
            "FirstName" : "First Name",
            "LastName" : "Last Name",
            "EmailAddress" : "Email Address",
            "Password" : "Password",
            "SignIn" : "Already have an account? Sign in",
            "SuccessLog" :"User Registerd Successfully"
        },
        "AppBarApp" : {
            "LogOutMessage" : "Are you sure ?",
            "Cancel" : "Cancel",
            "Ok" : "Ok",
            "AddHub" : "Add a Hub",
            "AddCuisine" : "Add a Cuisine",
            "AddPricingCategory" : "Add a Pricing Category",
            "AddOtherCategory" : "Add Other Category",
            "AddRestTypes" : "Add a Restaurant Type",
            "AddBrand" : "Add a Brand",
            "AddRest" : "Add a Restaurant",
            "AddPromotion" : "Add a Promotion"
        },
        "sideNav" : {
            "Dashboard" : "Dashboard",
            "Restaurants" : "Restaurants",
            "Notifications" : "Notifications",
            "RestaurantOptions" : "Restaurant Options",
            "Cuisines" : "Cuisines",
            "Brands" : "Brands",
            "Hubs" : "Hubs",
            "Segments" : "Segments",
            "PricingCategories" : "Pricing Categories",
            "OtherCat" : "Other Categories"
        },
        "BrandCreate" : {
            "ImageNotAdded" : "Please Add a Image for the Brand Before Submitting",
            "BrandCreate" : "Brand is successfully created",
            "BrandExists" : "Brand Already Exists with this name",
            "Brand" : "Brand",
            "AddBrand" : "Add a Brand",
            "BrandName" : "Brand Name",
            "BrandDesc" : "Brand Description",
            "AddImage" : "Add a Brand Image",
            "Create" : "Create"
        },
        "BrandEdit" : {
            "EditSuccess" : "The Brand is successfully edited",
            "AlreadyExists" : "Brand Already Exists with this name",
            "Brand" : "Brand",
            "EditBrand" :"Edit Brand",
            "BrandName" : "Brand Name",
            "BrandDesc" : "Brand Description",
            "AddImage" : "Add a Brand Image",
            "Edit" : "Edit"
        },
        "BrandTable" : {
            "BrandList" : "Brand List",
            "BrandName" : "Brand Name",
            "BrandRestCount" : "Brand Restaurant Count",
            "BrandImage" : "Brand Image",
            "Actions" : "Actions"
        },
        "PricingCategory" : {
            "ImageNotAdded" : "Please Add a Image for the Pricing Category Before Submitting",
            "Success" : "Pricing Category Successfully Created",
            "AlreadyExists" : "Pricing Category Already Exists with the Name",
            "PrcingCategory" : "Restaurant Pricing Category",
            "PricingType" : "Pricing Category Name",
            "PricingDesc" : "Pricing Category Description",
            "AddImage" : "Add a Picing Category Image",
            "Create" : "Create"

        },
        "PricingCatEdit" : {
            "Success" : "Pricing Category Successfully Edited",
            "AlreadyExists" :  "A Pricing Category already Exists with the name",
            "PrcingCategory" : "Edit Pricing Category",
            "PricingType" : "Pricing Category Name",
            "PricingDesc" : "Pricing Category Description",
            "AddImage" : "Add a Picing Category Image",
            "Edit" : "Edit"

        },
        "PricingCatTable" : {
            "PricingList" : "Pricing Category List",
            "Name" :  "Pricing Category Name",
            "Image" : "Image",
            "Actions" : "Actions",
        },
        "HubCreate" : {
            "LocNotAdded" : "Please Add a Location for the Hub Before Submitting",
            "SubLocNotAdded" : "Please Add a SubLocation for the Hub Before Submitting",
            "ImageNotAdded" : "Please Add a Image for the Hub Before Submitting",
            "Success" : "Hub Created Successfully",
            "AlreadyExists" : "The Hub already Exists with the same name",
            "Hubs" : "Hubs",
            "CreateHub" : "Create a Hub",
            "HubName" : "Hub Name",
            "HubDesc" : "Hub Description",
            "HubLoc" : "Location Name",
            "HubSubLoc" : "Sublocation Name",
            "AddImage" : "Add a Hub Image",
            "Create" : "Create"
        },
        "HubEdit" : {
            "LocNotAdded" : "Please Add a Location for the Hub Before Submitting",
            "SubLocNotAdded" : "Please Add a SubLocation for the Hub Before Submitting",
            "Success" : "Hub Edited Successfully",
            "AlreadyExists" : "The Hub already Exists with the same name",
            "Hubs" : "Hubs",
            "CreateHub" : "Edit a Hub",
            "HubName" : "Hub Name",
            "HubDesc" : "Hub Description",
            "HubLoc" : "Location Name",
            "HubSubLoc" : "Sublocation Name",
            "AddImage" : "Add a Hub Image",
            "Edit" : "Edit"

        },
        "HubTable" : {
            "Hubs" : "Hubs",
            "HubList" : "Hub List",
            "HubName" : "Hub Name",
            "HubDesc" : "Hub Description",
            "HubLoc" : "Location Name",
            "HubSubLoc" : "Sublocation Name",
            "HubRestCount" : "Hub Restaurant Count",
            "HubImage" : "Hub Image",
            "Actions" : "Actions"
        },
        "CuisineCreate" : {
            "AlreadyExist" : "A Cuisine already Exists with the name",
            "ImageNotAdded" : "Please Add Image Before Submitting",
            "Success" : "Cuisine Created Successfully",
            "Cuisine" : "Cuisine",
            "CreateCuisine" : "Create a Cuisine",
            "CuisineName" : "Cuisine Name",
            "CuisineDesc" : "Cuisine Description",
            "CuisineImage" : "Add a Cuisine Image",
            "Create" : "Create"
        },
        "CuisineEdit" : {
            "AlreadyExist" : "A Cuisine already Exists with the name",
            "Success" : "Cuisine Edited Successfully",
            "Cuisine" : "Cuisine",
            "EditCuisine" : "Edit a Cuisine",
            "CuisineName" : "Cuisine Name",
            "CuisineDesc" : "Cuisine Description",
            "CuisineImage" : "Add a Cuisine Image",
            "Edit" : "Edit"
        },
        "CuisineTable" : {
            "CuisineList" : "Cuisine List",
            "CuisineName" : "Cuisine Name",
            "CuisineImage" : "Cuisine Image",
            "Actions" : "Actions",
            "CuisineRestCount" : "Cuisine Restaurant Count"
        },
        "PromotionCreate" : {
            "AlreadyExist" : "Promotion with the same title exists",
            "Success" : "Promotion Created Successfully",
            "ErrorDate1" : "Action From or To date must me more than equal to current date!",
            "ErrorDate2" : "Action From date must be less then Activated To date!",
            "LocNotAdded" : "Please Add a Location for the Promotion Before Submitting",
            "SubLocNotAdded" : "Please Add a SubLocation for the Promotion Before Submitting",
            "ImageNotAdded" : "Please Add a Image for the Promotion Before Submitting",
            "Promotion" : "Promotion",
            "CreatePromotion" : "Create a Promotion",
            "PromotionTitle" : "Promotion Title",
            "PromotionContent" : "Promotion Content",
            "SendDate" : "Activated From",
            "ValidThrough" : "Activate To",
            "Location" : "LocationName",
            "SubLocation" : "SubLocationName",
            "PromotionalBanner" : "Add Promotional Banner",
            "Create" : "Create"
        },
        "PromotionEdit" : {
            "Promotion" : "Promotion",
            "CreatePromotion" : "Edit a Promotion",
            "PromotionTitle" : "Promotion Title",
            "PromotionContent" : "Promotion Content",
            "SendDate" : "Activated From",
            "ValidThrough" : "Activate To",
            "Location" : "LocationName",
            "SubLocation" : "SubLocationName",
            "PromotionalBanner" : "Edit Promotion Banner",
            "Edit" : "Edit"
        },
        "PromotionTable" : {
            "Promotion" : "Promotion",
            "PromotionList" : "PromotionList",
            "PromotionTitle" : "Promotion Title",
            "PromotionContent" : "Promotion Content",
            "SendDate" : "Activated From",
            "ValidThrough" : "Activate To",
            "Location" : "LocationName",
            "SubLocation" : "SubLocationName",
            "PromotionImage" : "Promotion Banner",
            "PromotionStatus" : "Prpmotion Status",
            "Actions" : "Actions",
            "StatusEdit" :  "Status updated successfully",
        },
        "OperatingHours" : {
            "OpenFrom" : "Open From",
            "OpenTo" : "Open To",
            "BreakFrom" : "Break From",
            "BreakTo" : "BreakTo",
            "AddOpHours" : " Add/Update Checked Operating Hours",
            "Weekday" : "Weekday",
            "Previous" : "Go to Previous Page",
            "Continue" : "Continue to Confirm Details"
        },
        "OtherCategoryCreate" : {
            "ImageNotAdded" : "Please Add Image before submit",
            "Success" : "New Other Category Type Created Successfully",
            "AlreadyExist" : "Category with this name Already Exists",
            "OtherCategories" : "Other Categories",
            "CreateCategory" : "Create a Category",
            "CategoryName" : "Category Name",
            "CategoryDesc" : "Category Description",
            "CategoryImage"  : "Add a Category Image",
            "Create" : "Create"

        },
        "OtherCategoryEdit" : {
            "Success" : "Category Type Edited Successfully",
            "AlreadyExist" : "Category with this name Already Exists",
            "OtherCategories" : "Other Categories",
            "CreateCategory" : "Edit a Category",
            "CategoryName" : "Category Name",
            "CategoryDesc" : "Category Description",
            "CategoryImage"  : "Add a Category Image",
            "Edit" : "Edit"

        },
        "OtherCategoryTable" : {
            "OtherCategories" : "Other Categories",
            "OtherCatList" : "Category List",
            "CategoryName" : "Category Name",
            "CategoryRestCount" : "Category Restaurant Count",
            "CategoryImage"  : "Category Image",
            "Actions" : "Actions"
        },
        "RecommendedMenu" : {
            "RecommendedMenu" : "RecommendedMenu",
            "MenuItem" : "Menu Item",
            "Price" : "Price",
            "AddMenu" : "Add Menu",
            "Actions" : "Actions",
            "Previous" : "Go to Previous Page",
            "Next": "Continue to Next Page"
        },
        "SegmentCreate" : {
            "ImageNotAdded" : "Please Add a Segment Image before Submitting",
            "Success" : "Segment Created Succesfully",
            "AlreadyExists" : "Segment Already Exists with the same name",
            "Segment" : "Restaurant Segment",
            "CreateSegment" : "Create A Segment",
            "SegmentName" : "Segment Name",
            "SegmentDesc": "Segment Description",
            "SegmentImage" : "Add a Segment Image",
            "Create" : "Create"
        },
        "SegmentEdit" : {
            "Success" : "Segment Edited Succesfully",
            "AlreadyExists" : "Segment Already Exists with the same name",
            "Segment" : "Restaurant Segment",
            "EditSegment" : "Edit A Segment",
            "SegmentName" : "Segment Name",
            "SegmentDesc": "Segment Description",
            "SegmentImage" : "Edit Segment Image",
            "Edit" : "Edit"
        },
        "SegmentTable" : {
            "Segment" : "Restaurant Segment",
            "SegmentList" : "Segment List",
            "SegmentName" : "Segment Name",
            "SegmentRestCoutn": "Segment Restaurant Count",
            "SegmentImage" : "Segment Image",
            "Actions" : "Actions"
        },
        "RestCreate" : {
            "MenuItemAlreadyAdded" : "Already Menu Item is added. If ypu want to update Price Values Please Delete and Create Again",
            "MenuItemNameError" : "Please Enter Menu Item Value to Add",
            "MenuItemPriceError" : "Please Enter Price Value to Add",
            "DiscountHourAlreadyAdded" : "Already Discount Hours is added. If ypu want to update Discount Values Please Delete and Create Again",
            "DiscountValueError" : "Please Enter Discount Value to Add",
            "DiscountHourError" : "Please Enter Discount Value to Add",
            "DiscountSeatError" : "Please Enter Number of Seats to be Added",
            "LocError" : "Please Add a Location for the Hub Before Submitting",
            "SubLocError" : "Please Add a SubLocation for the Hub Before Submitting",
            "CuisineError" : "Please Add a Cuisine for the Restaurant Before Submitting",
            "SegmentError" : "Please Add a Segement for the Restaurant Before Submitting",
            "LatError" : "Please Add the Latitude of the Restaurant Before Submitting",
            "LongError" : "Please Add the Longitude of the Restaurant Before Submitting",
            "NameError" : "Please Add the Rest Name Before Submitting",
            "ImageError" : "Please Add the Restaurant Images Before Submitting",
            "RestSuccess" : "Restaurant is Successfully Created",
            "Restaurant" : "Restaurant",
            "RestExists" : "Restaurant Already Exists with the same name",
            "ImageSizeError" : "Cannot Upload More than 5 Images for a restaurant",
            "CreateRest" : "Create a Restaurant",
            "AddDiscointHours" : "Add Restaurant Discount Hours",
            "AddRecommendedMenu" : "Add Restaurant Recommended Menu",
            "AddOpHours" : "Add Restaurant Operating Hours",
            "RestConfirm" : "Restaurant Create Confirmation",
            "RestSuccessEdit" : "Restaurant is Successfully Edited",
            "EditRes" : "Edit Restaurant",
            "EditDisc" : "Edit Restaurant Discount Hours",
            "EditRecMenu" : "Edit Restaurant Recommended Menu",
            "EditOppHours" : "Edit Restaurant Operating Hours",
            "EditRestComfirm" : "Restaurant Edit Confirmation" 
        },
        "RestBasic" : {
            "RestBasic" : "Restaurant Basic Details",
            "RestName" : "Restaurant Name",
            "RestEmailAddress" : "Email Addres",
            "ContactNumber" : "Contact Number",
            "PricingLevel" : "Pricing Level",
            "RestaurantLatitude" : "Restaurant Latitude",
            "RestaurantLongitude" : "Restaurant Longitude",
            "Payment" : "Payment Mode(Comma Separated)",
            "Spoken" : "Spoken Languages(Comma Separated)",
            "About" : "About",
            "SpecialConditions" : "Special Conditions",
            "Address" : "Address",
            "RestLocDetails" : "Restaurant Location Details",
            "RestLoc" : "Location Name",
            "SubLocationName" : "SubLocation Name",
            "HubName" : "Hub Name",
            "RestCatDet" : "Restaurant Categorisation Details",
            "Cusines" : "Cusines",
            "RestaurantTypes" : "Restaurant Types",
            "CostCategory" : "Cost Category",
            "Brand" : "Brand (if any)",
            "ImageAdd" : "Add Restaurant Images",
            "Continue" : "Continue",
        },
        "RestHappy" : {
            "AddDiscount" : "Add Discount",
            "Actions" : "Actions",
            "DiscountHours" : "Discount Hours",
            "DiscountValue" : "Discount Value",
            "SeatCount" : "Seat Count",
            "Previous" : "Previous",
            "Continue" : "Continue"
        },
        "RestRatings" : {
            "RestRating" : "Restuarant Rating List",
            "Id" : "Restaurant Id",
            "Comment" : "Rating Comment",
            "RatingOn" : "Rating On",
            "RatingBy" : "Rating By",
            "Rating" : "Rating"
        },
        "RestTable" : {
            "RestuarantList" : "Restuarant List",
            "RestName" : "Restaurant Name",
            "RestLoc" : "Restaurant Location",
            "RestSubLoc" : "Restaurant SubLocation",
            "RestaurantCuisine" : "Restaurant Cuisine",
            "RestaurantType" : "Restaurant Type",
            "RestaurantStatus" : "Restaurant Status",
            "RestRatings" : "Restaurant Ratings",
            "Rating" : "Rating",
            "Actions" : "Actions",
            "View" : "View"
        },
       
        
    },
    "ja" : {
        "SignIn": {
            "EmailAddress" : "Email Address(ja)",
            "Password" : "Password(ja)",
            "SignIn" : "Sign In(ja)",
            "SignUp" : "Don't have an account? Sign Up(ja)",
            "SuccessLog" : "User Logged In Successfully(ja)"
        },
        "SignUp" : {
            "SignUp" : "Sign up(ja)",
            "FirstName" : "First Name(ja)",
            "LastName" : "Last Name(ja)",
            "EmailAddress" : "Email Address(ja)",
            "Password" : "Password(ja)",
            "SignIn" : "Already have an account? Sign in(ja)",
            "SuccessLog" :"User Registerd Successfully(ja)"
        },
        "AppBarApp" : {
            "LogOutMessage" : "Are you sure ?",
            "Cancel" : "Cancel",
            "Ok" : "Ok",
            "AddHub" : "Add a Hub",
            "AddCuisine" : "Add a Cuisine",
            "AddPricingCategory" : "Add a Pricing Category",
            "AddOtherCategory" : "Add Other Category",
            "AddRestTypes" : "Add a Restaurant Type",
            "AddBrand" : "Add a Brand",
            "AddRest" : "Add a Restaurant",
            "AddPromotion" : "Add a Promotion"
        },
        "sideNav" : {
            "Dashboard" : "Dashboard",
            "Restaurants" : "Restaurants",
            "Notifications" : "Notifications",
            "RestaurantOptions" : "Restaurant Options",
            "Cuisines" : "Cuisines",
            "Brands" : "Brands",
            "Hubs" : "Hubs",
            "Segments" : "Segments",
            "PricingCategories" : "Pricing Categories",
            "OtherCat" : "Other Categories"
        }, 
        "BrandCreate" : {
            "ImageNotAdded" : "Please Add a Image for the Brand Before Submitting",
            "BrandCreate" : "Brand is successfully created",
            "BrandExists" : "Brand Already Exists with this name",
            "Brand" : "Brand",
            "AddBrand" : "Add a Brand",
            "BrandName" : "Brand Name",
            "BrandDesc" : "Brand Description",
            "AddImage" : "Add a Brand Image",
            "Create" : "Create"
        },
        "BrandEdit" : {
            "EditSuccess" : "The Brand is successfully edited",
            "AlreadyExists" : "Brand Already Exists with this name",
            "Brand" : "Brand",
            "EditBrand" :"Edit Brand",
            "BrandName" : "Brand Name",
            "BrandDesc" : "Brand Description",
            "AddImage" : "Add a Brand Image",
            "Edit" : "Edit"
        },
        "BrandTable" : {
            "BrandList" : "Brand List",
            "BrandName" : "Brand Name",
            "BrandRestCount" : "Brand Restaurant Count",
            "BrandImage" : "Brand Image",
            "Actions" : "Actions"
        },
        "PricingCategory" : {
            "ImageNotAdded" : "Please Add a Image for the Pricing Category Before Submitting",
            "Success" : "Pricing Category Successfully Created",
            "AlreadyExists" : "Pricing Category Already Exists with the Name",
            "PrcingCategory" : "Restaurant Pricing Category",
            "PricingType" : "Pricing Category Name",
            "PricingDesc" : "Pricing Category Description",
            "AddImage" : "Add a Picing Category Image",
            "Create" : "Create"

        },
        "PricingCatEdit" : {
            "Success" : "Pricing Category Successfully Edited",
            "AlreadyExists" :  "A Pricing Category already Exists with the name",
            "PrcingCategory" : "Edit Pricing Category",
            "PricingType" : "Pricing Category Name",
            "PricingDesc" : "Pricing Category Description",
            "AddImage" : "Add a Picing Category Image",
            "Edit" : "Edit"

        },
        "PricingCatTable" : {
            "PricingList" : "Pricing Category List",
            "Name" :  "Pricing Category Name",
            "Image" : "Image",
            "Actions" : "Actions",
        },
        "HubCreate" : {
            "LocNotAdded" : "Please Add a Location for the Hub Before Submitting",
            "SubLocNotAdded" : "Please Add a SubLocation for the Hub Before Submitting",
            "ImageNotAdded" : "Please Add a Image for the Hub Before Submitting",
            "Success" : "Hub Created Successfully",
            "AlreadyExists" : "The Hub already Exists with the same name",
            "Hubs" : "Hubs",
            "CreateHub" : "Create a Hub",
            "HubName" : "Hub Name",
            "HubDesc" : "Hub Description",
            "HubLoc" : "Location Name",
            "HubSubLoc" : "Sublocation Name",
            "AddImage" : "Add a Hub Image",
            "Create" : "Create"
        },
        "HubEdit" : {
            "LocNotAdded" : "Please Add a Location for the Hub Before Submitting",
            "SubLocNotAdded" : "Please Add a SubLocation for the Hub Before Submitting",
            "Success" : "Hub Edited Successfully",
            "AlreadyExists" : "The Hub already Exists with the same name",
            "Hubs" : "Hubs",
            "CreateHub" : "Edit a Hub",
            "HubName" : "Hub Name",
            "HubDesc" : "Hub Description",
            "HubLoc" : "Location Name",
            "HubSubLoc" : "Sublocation Name",
            "AddImage" : "Add a Hub Image",
            "Edit" : "Edit"

        },
        "HubTable" : {
            "Hubs" : "Hubs",
            "HubList" : "Hub List",
            "HubName" : "Hub Name",
            "HubDesc" : "Hub Description",
            "HubLoc" : "Location Name",
            "HubSubLoc" : "Sublocation Name",
            "HubRestCount" : "Hub Restaurant Count",
            "HubImage" : "Hub Image",
            "Actions" : "Actions"
        },
        "CuisineCreate" : {
            "AlreadyExist" : "A Cuisine already Exists with the name",
            "Success" : "Cuisine Created Successfully",
            "Cuisine" : "Cuisine",
            "CreateCuisine" : "Create a Cuisine",
            "CuisineName" : "Cuisine Name",
            "CuisineDesc" : "Cuisine Description",
            "CuisineImage" : "Add a Cuisine Image",
            "Create" : "Create"
        },
        "CuisineEdit" : {
            "AlreadyExist" : "A Cuisine already Exists with the name",
            "Success" : "Cuisine Edited Successfully",
            "Cuisine" : "Cuisine",
            "EditCuisine" : "Edit a Cuisine",
            "CuisineName" : "Cuisine Name",
            "CuisineDesc" : "Cuisine Description",
            "CuisineImage" : "Add a Cuisine Image",
            "Edit" : "Edit"
        },
        "CuisineTable" : {
            "CuisineList" : "Cuisine List",
            "CuisineName" : "Cuisine Name",
            "CuisineImage" : "Cuisine Image",
            "Actions" : "Actions",
            "CuisineRestCount" : "Cuisine Restaurant Count"
        },
        "PromotionCreate" : {
            "AlreadyExist" : "Promotion with the same title exists",
            "Success" : "Promotion Created Successfully",
            "ErrorDate1" : "Action From or To date must me more than equal to current date!",
            "ErrorDate2" : "Action From date must be less then Activated To date!",
            "LocNotAdded" : "Please Add a Location for the Promotion Before Submitting",
            "SubLocNotAdded" : "Please Add a SubLocation for the Promotion Before Submitting",
            "ImageNotAdded" : "Please Add a Image for the Promotion Before Submitting",
            "Promotion" : "Promotion",
            "CreatePromotion" : "Create a Promotion",
            "PromotionTitle" : "Promotion Title",
            "PromotionContent" : "Promotion Content",
            "SendDate" : "Activated From",
            "ValidThrough" : "Activate To",
            "Location" : "LocationName",
            "SubLocation" : "SubLocationName",
            "PromotionalBanner" : "Add Promotional Banner",
            "Create" : "Create"
        },
        "PromotionEdit" : {
            "Promotion" : "Promotion",
            "CreatePromotion" : "Edit a Promotion",
            "PromotionTitle" : "Promotion Title",
            "PromotionContent" : "Promotion Content",
            "SendDate" : "Activated From",
            "ValidThrough" : "Activate To",
            "Location" : "LocationName",
            "SubLocation" : "SubLocationName",
            "PromotionalBanner" : "Edit Promotion Banner",
            "Edit" : "Edit"
        },
        "PromotionTable" : {
            "Promotion" : "Promotion",
            "PromotionList" : "PromotionList",
            "PromotionTitle" : "Promotion Title",
            "PromotionContent" : "Promotion Content",
            "SendDate" : "Activated From",
            "ValidThrough" : "Activate To",
            "Location" : "LocationName",
            "SubLocation" : "SubLocationName",
            "PromotionImage" : "Promotion Banner",
            "PromotionStatus" : "Prpmotion Status",
            "Actions" : "Actions",
            "StatusEdit" :  "Status updated successfully",
        },
        "OperatingHours" : {
            "OperatingHours" : "OperatingHours",
            "OpenFrom" : "Open From",
            "OpenTo" : "Open To",
            "BreakFrom" : "Break From",
            "BreakTo" : "BreakTo",
            "AddOpHours" : " Add/Update Checked Operating Hours",
            "Weekday" : "Weekday",
            "Previous" : "Go to Previous Page",
            "Continue" : "Continue to Confirm Details"
        },
        "OtherCategoryCreate" : {
            "Success" : "New Other Category Type Created Successfully",
            "AlreadyExist" : "Category with this name Already Exists",
            "OtherCategories" : "Other Categories",
            "CreateCategory" : "Create a Category",
            "CategoryName" : "Category Name",
            "CategoryDesc" : "Category Description",
            "CategoryImage"  : "Add a Category Image",
            "Create" : "Create"

        },
        "OtherCategoryEdit" : {
            "Success" : "Category Type Edited Successfully",
            "AlreadyExist" : "Category with this name Already Exists",
            "OtherCategories" : "Other Categories",
            "CreateCategory" : "Edit a Category",
            "CategoryName" : "Category Name",
            "CategoryDesc" : "Category Description",
            "CategoryImage"  : "Add a Category Image",
            "Edit" : "Edit"

        },
        "OtherCategoryTable" : {
            "OtherCategories" : "Other Categories",
            "OtherCatList" : "Category List",
            "CategoryName" : "Category Name",
            "CategoryRestCount" : "Category Restaurant Count",
            "CategoryImage"  : "Category Image",
            "Actions" : "Actions"
        },
        "RecommendedMenu" : {
            "MenuItem" : "Menu Item",
            "Price" : "Price",
            "AddMenu" : "Add Menu",
            "Actions" : "Actions",
            "Previous" : "Go to Previous Page",
            "Next": "Continue to Next Page"
        },
        "SegmentCreate" : {
            "Success" : "Segment Created Succesfully",
            "AlreadyExists" : "Segment Already Exists with the same name",
            "Segment" : "Restaurant Segment",
            "CreateSegment" : "Create A Segment",
            "SegmentName" : "Segment Name",
            "SegmentDesc": "Segment Description",
            "SegmentImage" : "Add a Segment Image",
            "Create" : "Create"
        },
        "SegmentEdit" : {
            "Success" : "Segment Edited Succesfully",
            "AlreadyExists" : "Segment Already Exists with the same name",
            "Segment" : "Restaurant Segment",
            "EditSegment" : "Edit A Segment",
            "SegmentName" : "Segment Name",
            "SegmentDesc": "Segment Description",
            "SegmentImage" : "Edit Segment Image",
            "Edit" : "Edit"
        },
        "SegmentTable" : {
            "Segment" : "Restaurant Segment",
            "SegmentList" : "Segment List",
            "SegmentName" : "Segment Name",
            "SegmentRestCoutn": "Segment Restaurant Count",
            "SegmentImage" : "Segment Image",
            "Actions" : "Actions"
        },
        "RestCreate" : {
            "MenuItemAlreadyAdded" : "Already Menu Item is added. If ypu want to update Price Values Please Delete and Create Again",
            "MenuItemNameError" : "Please Enter Menu Item Value to Add",
            "MenuItemPriceError" : "Please Enter Price Value to Add",
            "DiscountHourAlreadyAdded" : "Already Discount Hours is added. If ypu want to update Discount Values Please Delete and Create Again",
            "DiscountValueError" : "Please Enter Discount Value to Add",
            "DiscountHourError" : "Please Enter Discount Value to Add",
            "DiscountSeatError" : "Please Enter Number of Seats to be Added",
            "LocError" : "Please Add a Location for the Hub Before Submitting",
            "SubLocError" : "Please Add a SubLocation for the Hub Before Submitting",
            "CuisineError" : "Please Add a Cuisine for the Restaurant Before Submitting",
            "SegmentError" : "Please Add a Segement for the Restaurant Before Submitting",
            "LatError" : "Please Add the Latitude of the Restaurant Before Submitting",
            "LongError" : "Please Add the Longitude of the Restaurant Before Submitting",
            "NameError" : "Please Add the Rest Name Before Submitting",
            "ImageError" : "Please Add the Restaurant Images Before Submitting",
            "RestSuccess" : "Restaurant is Successfully Created",
            "RestExists" : "Restaurant Already Exists with the same name",
            "ImageSizeError" : "Cannot Upload More than 5 Images for a restaurant",
            "CreateRest" : "Create a Restaurant",
            "AddDiscointHours" : "Add Restaurant Discount Hours",
            "AddRecommendedMenu" : "Add Restaurant Recommended Menu",
            "AddOpHours" : "Add Restaurant Operating Hours",
            "RestConfirm" : "Restaurant Create Confirmation",
            "RestSuccessEdit" : "Restaurant is Successfully Edited",
            "EditRes" : "Edit Restaurant",
            "EditDisc" : "Edit Restaurant Discount Hours",
            "EditRecMenu" : "Edit Restaurant Recommended Menu",
            "EditOppHours" : "Edit Restaurant Operating Hours",
            "EditRestComfirm" : "Restaurant Edit Confirmation" 
        },
        "RestBasic" : {
            "RestBasic" : "Restaurant Basic Details",
            "RestName" : "Restaurant Name",
            "RestEmailAddress" : "Email Addres",
            "ContactNumber" : "Contact Number",
            "PricingLevel" : "Pricing Level",
            "RestaurantLatitude" : "Restaurant Latitude",
            "RestaurantLongitude" : "Restaurant Longitude",
            "Payment" : "Payment Mode(Comma Separated)",
            "Spoken" : "Spoken Languages(Comma Separated)",
            "About" : "About",
            "SpecialConditions" : "Special Conditions",
            "Address" : "Address",
            "RestLocDetails" : "Restaurant Location Details",
            "RestLoc" : "Location Name",
            "SubLocationName" : "SubLocation Name",
            "HubName" : "Hub Name",
            "RestCatDet" : "Restaurant Categorisation Details",
            "Cusines" : "Cusines",
            "RestaurantTypes" : "Restaurant Types",
            "CostCategory" : "Cost Category",
            "Brand" : "Brand (if any)",
            "ImageAge" : "Add Restaurant Images",
            "Continue" : "Continue",
            "Submit" : "Submit",
            "Previous" : "Previous"
        },
        "RestHappy" : {
            "Submit" : "Submit",
            "AddDiscount" : "Add Discount",
            "Actions" : "Actions",
            "DiscountHours" : "Discount Hours",
            "DiscountValue" : "Discount Value",
            "SeatCount" : "Seat Count",
            "Previous" : "Previous",
            "Continue" : "Continue"
        },
        "RestRatings" : {
            "RestRating" : "Restuarant Rating List",
            "Id" : "Restaurant Id",
            "Comment" : "Rating Comment",
            "RatingOn" : "Rating On",
            "RatingBy" : "Rating By",
            "Rating" : "Rating"
        },
        "RestTable" : {
            "RestuarantList" : "Restuarant List",
            "RestName" : "Restaurant Name",
            "RestLoc" : "Restaurant Location",
            "RestSubLoc" : "Restaurant SubLocation",
            "RestaurantCuisine" : "Restaurant Cuisine",
            "RestaurantType" : "Restaurant Type",
            "RestaurantStatus" : "Restaurant Status",
            "RestRatings" : "Restaurant Ratings",
            "Rating" : "Rating",
            "Actions" : "Actions",
            "View" : "View"
        },
       
        
    }
}
]

const lang = {
    json
 }

 export default lang